/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import App5.Escena;
import Modelo.HeapSort;
import Modelo.InsertSort;
import Modelo.MetodosVarios;
import Modelo.Mmatriz;
import Modelo.Nodo;
import Modelo.QuickSort;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andres
 */
public class Principal extends javax.swing.JFrame implements Runnable {

    MetodosVarios metodos = new MetodosVarios();
    Escena e = new Escena();
    QuickSort quickSort = new QuickSort();
    InsertSort insertSort = new InsertSort();
    HeapSort heapsort = new HeapSort();
    Mmatriz multMatriz = new Mmatriz();
    int[] arreglo = {5, 7, 8, 5, 4, 1, 3, 6, 8, 10, 35};
    Panelprueba p;
    int lineaActual = -1;
    int indexEjecucion = -1;
    DefaultTableModel modelTableExcecution;
    DefaultListModel<String> modelListVariables;
    private int algoritmo = 0;
    boolean pausar = false;
    private final Object GUI_INITIALIZATION_MONITOR = new Object();
    Thread thagl = new Thread(this);

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        inicializarTableModel();
        inicializarListVariableModel();

    }

    private LinkedList<String> listarVariablesRegistro(HashMap<String, String> variables) {
        LinkedList<String> vars = new LinkedList<>();
        for (String llave : variables.keySet()) {
            vars.add(llave + " = " + variables.get(llave));
        }
        return vars;
    }

    private void inicializarListVariableModel() {
        this.modelListVariables = new DefaultListModel<>();
        this.listVariables.setModel(modelListVariables);
    }

    private void inicializarTableModel() {
        modelTableExcecution = new DefaultTableModel();
        modelTableExcecution.addColumn("Lineas ejecutadas");
        modelTableExcecution.addColumn("Identificador ambiente");
        modelTableExcecution.addColumn("Algoritmo");
        this.tableEjecucion.setModel(modelTableExcecution);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaalgoritmos = new javax.swing.JList();
        btnEjecutarAlg = new javax.swing.JButton();
        scrollTableExcecution = new javax.swing.JScrollPane();
        tableEjecucion = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        listVariables = new javax.swing.JList();
        txtEntradaDAtos = new javax.swing.JTextField();
        btnEntradaDatos = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        panelprueba1 = new Vista.Panelprueba();
        btnQuickSort = new javax.swing.JButton();
        btnInserSort = new javax.swing.JButton();
        btnHeapSort = new javax.swing.JButton();
        btnMultMatrix = new javax.swing.JButton();
        btnLineaAnterior = new javax.swing.JButton();
        btnpausa = new javax.swing.JButton();
        btncontinuar = new javax.swing.JButton();
        btnautomatico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaalgoritmos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        listaalgoritmos.setEnabled(false);
        jScrollPane1.setViewportView(listaalgoritmos);

        btnEjecutarAlg.setText("Siguiente");
        btnEjecutarAlg.setEnabled(false);
        btnEjecutarAlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarAlgActionPerformed(evt);
            }
        });

        tableEjecucion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "lineas ejecutadas", "id ambiente", "algoritmo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableEjecucion.setEnabled(false);
        tableEjecucion.getTableHeader().setReorderingAllowed(false);
        scrollTableExcecution.setViewportView(tableEjecucion);

        listVariables.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listVariables.setEnabled(false);
        jScrollPane2.setViewportView(listVariables);

        txtEntradaDAtos.setEnabled(false);

        btnEntradaDatos.setText("Procesar entrada de datos");
        btnEntradaDatos.setEnabled(false);
        btnEntradaDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaDatosActionPerformed(evt);
            }
        });

        panelprueba1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelprueba1Layout = new javax.swing.GroupLayout(panelprueba1);
        panelprueba1.setLayout(panelprueba1Layout);
        panelprueba1Layout.setHorizontalGroup(
            panelprueba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1815, Short.MAX_VALUE)
        );
        panelprueba1Layout.setVerticalGroup(
            panelprueba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(panelprueba1);

        btnQuickSort.setText("QuickSort");
        btnQuickSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickSortActionPerformed(evt);
            }
        });

        btnInserSort.setText("InsertSort");
        btnInserSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserSortActionPerformed(evt);
            }
        });

        btnHeapSort.setText("HeapSort");
        btnHeapSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHeapSortActionPerformed(evt);
            }
        });

        btnMultMatrix.setText("Multiplicacion de matrices");
        btnMultMatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultMatrixActionPerformed(evt);
            }
        });

        btnLineaAnterior.setText("Anterior");
        btnLineaAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLineaAnteriorActionPerformed(evt);
            }
        });

        btnpausa.setText("Pausa");
        btnpausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpausaActionPerformed(evt);
            }
        });

        btncontinuar.setText("Continuar");
        btncontinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncontinuarActionPerformed(evt);
            }
        });

        btnautomatico.setBackground(new java.awt.Color(102, 0, 0));
        btnautomatico.setForeground(new java.awt.Color(255, 255, 255));
        btnautomatico.setText("automatico");
        btnautomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnautomaticoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTableExcecution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnQuickSort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInserSort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHeapSort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMultMatrix)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEntradaDAtos)
                .addGap(18, 18, 18)
                .addComponent(btnEntradaDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEjecutarAlg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLineaAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnautomatico, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnpausa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncontinuar)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuickSort)
                    .addComponent(btnInserSort)
                    .addComponent(btnHeapSort)
                    .addComponent(btnMultMatrix)
                    .addComponent(txtEntradaDAtos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEntradaDatos)
                    .addComponent(btnEjecutarAlg)
                    .addComponent(btnLineaAnterior)
                    .addComponent(btnpausa)
                    .addComponent(btncontinuar)
                    .addComponent(btnautomatico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollTableExcecution, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ejecutarEstado(LinkedList<LinkedList<HashMap<String, String>>> estados) {
        lineaActual = Integer.parseInt(estados.get(indexEjecucion).get(0).get("lineaSiguiente"));

        modelTableExcecution.insertRow(0, new Object[]{indexEjecucion, estados.get(indexEjecucion).get(0).get("idMio"), estados.get(indexEjecucion).get(0).get("nombre")});
        LinkedList<String> variables = this.listarVariablesRegistro(estados.get(indexEjecucion).get(1));

        panelprueba1.setAmbiente(estados.get(indexEjecucion).get(0).get("idMio"));
        //this.graficarArbol(metodos.generarNodos(estados), Integer.parseInt(estados.get(indexEjecucion).get(0).get("idMio")));
        panelprueba1.repaint();

        modelListVariables.removeAllElements();
        for (String variable : variables) {
            modelListVariables.addElement(variable);
        }
        this.tableEjecucion.setRowSelectionInterval(0, 0);

        this.listaalgoritmos.setSelectedIndex(lineaActual);
    }

    private void btnEjecutarAlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarAlgActionPerformed
        if (this.algoritmo == 1) {
            if (indexEjecucion < quickSort.getRegistroAmbientes().size() - 1) {
                indexEjecucion++;
                this.ejecutarEstado(quickSort.getRegistroAmbientes());
            }
        } else if (this.algoritmo == 2) {
            if (indexEjecucion < insertSort.getRegistroAmbientes().size() - 1) {
                indexEjecucion++;
                this.ejecutarEstado(insertSort.getRegistroAmbientes());

            }
        } else if (this.algoritmo == 3) {
            if (indexEjecucion < heapsort.getRegistroAmbientes().size() - 1) {
                indexEjecucion++;
                this.ejecutarEstado(heapsort.getRegistroAmbientes());
            }

        } else if (this.algoritmo == 4) {
            if (indexEjecucion < multMatriz.getRegistroAmbientes().size() - 1) {
                indexEjecucion++;
                this.ejecutarEstado(multMatriz.getRegistroAmbientes());
            }

        }
    }//GEN-LAST:event_btnEjecutarAlgActionPerformed

    private void btnEntradaDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaDatosActionPerformed
        if (!txtEntradaDAtos.getText().equalsIgnoreCase("")) {
            if (this.algoritmo == 1) {
                String[] stringArray = this.txtEntradaDAtos.getText().split(",");
                this.arreglo = new int[stringArray.length];
                for (int i = 0; i < stringArray.length; i++) {
                    arreglo[i] = Integer.parseInt(stringArray[i]);
                }
                quickSort.QuickSort(arreglo);

                this.listaalgoritmos.setSelectedIndex(lineaActual);

                panelprueba1.setarbol(e.Escena(metodos.generarNodos(quickSort.getRegistroAmbientes())));
                //this.graficarArbol(metodos.generarNodos(quickSort.getRegistroAmbientes()), 1);
                this.listVariables.setEnabled(true);
                this.btnEjecutarAlg.setEnabled(true);

            } else if (this.algoritmo == 2) {
                String[] stringArray = this.txtEntradaDAtos.getText().split(",");
                this.arreglo = new int[stringArray.length];
                for (int i = 0; i < stringArray.length; i++) {
                    arreglo[i] = Integer.parseInt(stringArray[i]);
                }
                this.insertSort.Sort(arreglo);

                this.listaalgoritmos.setSelectedIndex(lineaActual);

                panelprueba1.setarbol(e.Escena(metodos.generarNodos(this.insertSort.getRegistroAmbientes())));
                this.listVariables.setEnabled(true);
                this.btnEjecutarAlg.setEnabled(true);
            } else if (this.algoritmo == 3) {
                String[] stringArray = this.txtEntradaDAtos.getText().split(",");
                this.arreglo = new int[stringArray.length];
                for (int i = 0; i < stringArray.length; i++) {
                    arreglo[i] = Integer.parseInt(stringArray[i]);
                }
                this.heapsort.heapSort(arreglo);

                this.listaalgoritmos.setSelectedIndex(lineaActual);

                panelprueba1.setarbol(e.Escena(metodos.generarNodos(this.heapsort.getRegistroAmbientes())));
                this.listVariables.setEnabled(true);
                this.btnEjecutarAlg.setEnabled(true);
            } else if (this.algoritmo == 4) {
                String[] stringArray = this.txtEntradaDAtos.getText().split(",");
                this.arreglo = new int[stringArray.length];
                for (int i = 0; i < stringArray.length; i++) {
                    arreglo[i] = Integer.parseInt(stringArray[i]);
                }
                this.multMatriz.mult(arreglo);

                this.listaalgoritmos.setSelectedIndex(lineaActual);

                panelprueba1.setarbol(e.Escena(metodos.generarNodos(this.multMatriz.getRegistroAmbientes())));
                this.listVariables.setEnabled(true);
                this.btnEjecutarAlg.setEnabled(true);
            }

        }
    }//GEN-LAST:event_btnEntradaDatosActionPerformed

    private void btnMultMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultMatrixActionPerformed
        seleccionarAlgoritmo("Algoritmos/Multiplicaionmatrices");
        this.algoritmo = 4;
    }//GEN-LAST:event_btnMultMatrixActionPerformed

    private void btnQuickSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickSortActionPerformed
        seleccionarAlgoritmo("Algoritmos/QuickSort");
        this.algoritmo = 1;
    }//GEN-LAST:event_btnQuickSortActionPerformed

    private void btnInserSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserSortActionPerformed
        seleccionarAlgoritmo("Algoritmos/InsertSort");
        this.algoritmo = 2;
    }//GEN-LAST:event_btnInserSortActionPerformed

    private void btnHeapSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHeapSortActionPerformed
        seleccionarAlgoritmo("Algoritmos/HeapSort");
        this.algoritmo = 3;
    }//GEN-LAST:event_btnHeapSortActionPerformed

    private void btnLineaAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLineaAnteriorActionPerformed
        if (this.algoritmo == 1) {
            if (indexEjecucion > 0) {
                indexEjecucion--;
                this.ejecutarEstado(this.quickSort.getRegistroAmbientes());
            }
        } else if (this.algoritmo == 2) {
            if (indexEjecucion > 0) {
                indexEjecucion--;
                this.ejecutarEstado(this.insertSort.getRegistroAmbientes());
            }
        } else if (this.algoritmo == 3) {
            if (indexEjecucion > 0) {
                indexEjecucion--;
                this.ejecutarEstado(this.heapsort.getRegistroAmbientes());
            }
        } else if (this.algoritmo == 4) {
            if (indexEjecucion > 0) {
                indexEjecucion--;
                this.ejecutarEstado(this.multMatriz.getRegistroAmbientes());
            }
        }
    }//GEN-LAST:event_btnLineaAnteriorActionPerformed

    private void btnpausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpausaActionPerformed

        try {
            pausa();
        } catch (InterruptedException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnpausaActionPerformed

    private void btncontinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncontinuarActionPerformed
        continuar();
    }//GEN-LAST:event_btncontinuarActionPerformed

    private void btnautomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnautomaticoActionPerformed
        thagl.start();
    }//GEN-LAST:event_btnautomaticoActionPerformed

    private void graficarArbol(LinkedList<Nodo> nodos, int idAmbiente) {

        for (int i = 0; i < nodos.size(); i++) {

            //arbil.insertarhijo(Integer.parseInt(nodos.get(i).getidPropio()),Integer.parseInt(nodos.get(i).getidPadre()))
        }
        //arbol.grafigararbol
    }

    private void seleccionarAlgoritmo(String url) {
        DefaultListModel modelo = new DefaultListModel();
        File a = new File(url);
        FileReader fr;
        try {
            fr = new FileReader(a);
            BufferedReader br = new BufferedReader(fr);
            String linea;
            while ((linea = br.readLine()) != null) {
                modelo.addElement(linea);
            }
            this.listaalgoritmos.setModel(modelo);
            this.listaalgoritmos.setEnabled(true);
            this.txtEntradaDAtos.setEnabled(true);
            this.btnEntradaDatos.setEnabled(true);
            lineaActual = -1;
            indexEjecucion = -1;
            this.borrarTabla();
            this.listVariables.removeAll();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void borrarTabla() {
        int rows = this.modelTableExcecution.getRowCount();
        this.modelTableExcecution.setRowCount(0);
//        for (int i = 0; i < rows; i++) {
//            this.modelTableExcecution.removeRow(i);
//
//        }
//        for (int b : this.modelTableExcecution.setro) {
//            
//        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEjecutarAlg;
    private javax.swing.JButton btnEntradaDatos;
    private javax.swing.JButton btnHeapSort;
    private javax.swing.JButton btnInserSort;
    private javax.swing.JButton btnLineaAnterior;
    private javax.swing.JButton btnMultMatrix;
    private javax.swing.JButton btnQuickSort;
    private javax.swing.JButton btnautomatico;
    private javax.swing.JButton btncontinuar;
    private javax.swing.JButton btnpausa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listVariables;
    private javax.swing.JList listaalgoritmos;
    private Vista.Panelprueba panelprueba1;
    private javax.swing.JScrollPane scrollTableExcecution;
    private javax.swing.JTable tableEjecucion;
    private javax.swing.JTextField txtEntradaDAtos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) {
            switch (algoritmo) {
                case 1:

                   

                    while (indexEjecucion < quickSort.getRegistroAmbientes().size() - 1) {
                        checkForPaused();
                        indexEjecucion++;
                        this.ejecutarEstado(quickSort.getRegistroAmbientes());
                        try {
                            Thread.sleep(500);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }

                case 2:
                    checkForPaused();
                    while (indexEjecucion < insertSort.getRegistroAmbientes().size() - 1) {
                        checkForPaused();
                        indexEjecucion++;
                        this.ejecutarEstado(insertSort.getRegistroAmbientes());
                        try {
                            Thread.sleep(500);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }

                case 3:
                    
                    while (indexEjecucion < heapsort.getRegistroAmbientes().size() - 1) {
                        checkForPaused();
                        indexEjecucion++;
                        this.ejecutarEstado(heapsort.getRegistroAmbientes());
                        try {
                            Thread.sleep(500);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }

                case 4:
                    
                    while (indexEjecucion < multMatriz.getRegistroAmbientes().size() - 1) {
                        checkForPaused();
                        indexEjecucion++;
                        this.ejecutarEstado(multMatriz.getRegistroAmbientes());
                        try {
                            Thread.sleep(500);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }

            }
        }
    }

    public synchronized void pausa() throws InterruptedException {
        pausar = true;
    }

    public synchronized void continuar() {
        synchronized (GUI_INITIALIZATION_MONITOR) {
            pausar = false;
            GUI_INITIALIZATION_MONITOR.notify();
        }
    }

    private void checkForPaused() {
        synchronized (GUI_INITIALIZATION_MONITOR) {
            while (pausar) {
                try {
                    GUI_INITIALIZATION_MONITOR.wait();
                } catch (Exception e) {
                }
            }
        }
    }
}
